spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/colis
    username: postgres
    password: superuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

media:
  images:
    imagesProfile:
      directory: ../imagesProfile
      url: http://192.168.11.102:8080/imagesProfile/
      path: /imagesProfile

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#        expiration: 86400000
      expiration: 120000
      refresh-token:
        expiration: 604800000