spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/colis
    username: postgres
    password: superuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
