spring:
  datasource:
    url: jdbc:postgresql://db:5437/colisdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
media:
  images:
    images-profile:
      directory: ../imagesProfile
      url: http://192.168.11.101:8080/imagesProfile/